[server]
port = 8560
baseUrlPath = ""
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#00d4ff"
backgroundColor = "#0a0a0a"
secondaryBackgroundColor = "#121212"
textColor = "#f0f0f0"
font = "sans serif"

[browser]
gatherUsageStats = false
